[package]
name = "roundabout-simulation"
version = "0.1.0"
edition = "2024"

[dependencies]
# Note: Do not use dynamic linking when publishing release builds.
bevy = { version = "0.19.0", features = ["dynamic_linking"] }
bevy-inspector-egui = "0.37.0"
bevy_egui = "0.42.0"
bimap = "0.6.3"
clap = { version = "4.6.6", features = ["derive"] }
rand = "0.10.1"
rand_distr = "0.6.0"
uom = "0.38.0"

# Enable a small amount of optimization in debug mode.
[profile.dev]
opt-level = 1

# Fully optimize dependencies so they run at full speed.
[profile.dev.package."*"]
opt-level = 3
